server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      #      register-with-eureka: false
      fetch-registry: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transacctiontest?serverTimezone=GMT%2B8
    username: root
    password: root
    driver: com.jdbc.mysql.Driver
  application:
    name: serviceB
  cloud:
    alibaba:
      seata:
        tx-service-group: my_service_test_group
tx-lcn:
  client:
    manager-address: localhost:8070
#  logger:
#    enabled: true
#    jdbc-url: jdbc:mysql://localhost:3306/tx-manager?serverTimezone=GMT%2B8
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
ribbon:
  MaxAutoRetriesNextServer: 0
  message:
    netty:
      reconnect-count: 10
      reconnect-delay: 1000
feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream