eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
#  instance:
#    health-check-url-path: /actuator/health
#    instance-id: ${eureka.instance.ip-address}:${server.port}
#    ip-address: localhost
#    lease-expiration-duration-in-seconds: 30
#    lease-renewal-interval-in-seconds: 10
#    prefer-ip-address: true
ribbon:
  MaxAutoRetriesNextServer: 0
server:
  port: 9002
spring:
  application:
    name: serviceTest
  datasource:
    driver: com.jdbc.mysql.Driver
    password: root
    url: jdbc:mysql://localhost:3306/transacctiontest?serverTimezone=GMT%2B8
    username: root
  cloud:
    alibaba:
      seata:
        tx-service-group: my_service_test_group
#tx-lcn:
#  client:
#    manager-address: localhost:8070
#  message:
#    netty:
#      reconnect-count: 10
#      reconnect-delay: 1000
feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream